# fly.toml app configuration file generated for tsoha-dogparks on 2024-04-07T16:06:45+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tsoha-dogparks'
primary_region = 'ams'

[build]
  builder = "paketobuildpacks/builder:full"

[env]
  PORT = "5000"


[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
